spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codejava_authentication
    username: root
    password: Noobinmysql10809$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8090